### ISSUE TITLE
Ansible-lint not  resolve properly collections from meta/main.yml role file

### ISSUE THREAD

**Issue by Eugen1987** [ansible-community/ansible-lint#1122]
##### Summary
We have a playbook that import a role called:  azure-sql. The role is very simple and have one task:
``` yaml
   - name: Retrieve dba password
      azure_rm_keyvaultsecret_info:
        name: "{{ secret }}"
        vault_uri: "{{ uri }}"
      register: _secret
```
In that role we have a main.yml meta file with collection we want to use.
``` yaml
collections:
  - azure.azcollection
```
when we launch the playbook all work ok. When we launch ansible-lint, it fails with the following error: 
```
CRITICAL Couldn't parse task at /Users/topi/roles/azure-sql/tasks/user.yml:23 (couldn't resolve module/action 'azure_rm_keyvaultsecret_info'. This often indicates a misspelling, missing collection, or incorrect module path.)
{ 'azure_rm_keyvaultsecret_info': { '__file__': '/Users/topi/roles/azure-sql/tasks/user.yml,
                                    '__line__': 25,
                                    'name': '{{ secret }}',
                                    'vault_uri': '{{ uri }}',
  'name': 'Retrieve dba password',
  'no_log': True,
  'register': '_dbapw'}
```
If we add azure.azcollection to the module name like this:
``` yaml
   - name: Retrieve dba password
      azure.azcollection.azure_rm_keyvaultsecret_info:
        name: "{{ secret }}"
        vault_uri: "{{ uri }}"
      register: _secret
```
ansible-lint work fine.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
ansible 2.10.3
  config file = /Users/topi/workplace/dap-platform-ops/ansible.cfg
  configured module search path = ['/Users/topi/workplace/dap-platform-ops/library']
  ansible python module location = /Users/topi/workplace/demo/lib/python3.8/site-packages/ansible
  executable location = /Users/topi/workplace/demo/bin/ansible
  python version = 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) [Clang 6.0 (clang-600.0.57)]

ansible-lint --version
ansible-lint 4.3.7
>  >

```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Darwin topi 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

##### STEPS TO REPRODUCE

create a playbook called test with the following content:
``` yaml
    - name: Sql secret
      include_role:
        name: azure-sql
      vars:
        secret: "{{ sql_secret }}"
        uri: "{{ sql_keyvault_uri }}
```
create a role called azure-sql  with the following content:
``` yaml
   - name: Retrieve dba password
      azure_rm_keyvaultsecret_info:
        name: "{{ secret }}"
        vault_uri: "{{ uri }}"
      register: _secret
```
In that role in meta/main.yml file set the collection of wich the module azure_rm_keyvaultsecret_info belong.
``` yaml
collections:
  - azure.azcollection
```

```console (paste below)

```

##### Desired Behaviour

When we launch ansible-lint it must pass.

##### Actual Behaviour

When we launch ansible-lint, it fails with the following error: 
```
CRITICAL Couldn't parse task at /Users/topi/roles/azure-sql/tasks/user.yml:23 (couldn't resolve module/action 'azure_rm_keyvaultsecret_info'. This often indicates a misspelling, missing collection, or incorrect module path.)
{ 'azure_rm_keyvaultsecret_info': { '__file__': '/Users/topi/roles/azure-sql/tasks/user.yml,
                                    '__line__': 25,
                                    'name': '{{ secret }}',
                                    'vault_uri': '{{ uri }}',
  'name': 'Retrieve dba password',
  'no_log': True,
  'register': '_dbapw'}
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
