### ISSUE TITLE
Error thrown for task marked with noqa suppression

### ISSUE THREAD

**Issue by nre-ableton** [ansible-community/ansible-lint#1367]
##### Summary

In one of our playbooks, we have the following task:

```yaml
- name: Display list of changes
  delegate_to: localhost
  command: "git log --no-merges --oneline {{ host_revision.0 }}..HEAD"  # noqa command-instead-of-module
  register: git_log_cmd
  changed_when: false
```

ansible-lint 5.0.0 prints `diff.yml:32: command-instead-of-module git used in place of git module`. I have not yet tried on version 5.0.1, since it seems the release hasn't yet found its way to pypi, however I also verified the behavior on commit 9dbccb8f19addeda53ac7eb6d52ac000b9698032 in the `master` branch. I also tried moving the suppression to the same line as the task name, but that didn't work either.

Strangely, we have a handful of other similar tasks in other places which also have the `noqa command-instead-of-module` suppression and are correctly ignored. The only difference I can spot is that this task is in a top-level playbook and not part of a role or other task file.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console
$ ansible --version
ansible 2.10.5
  config file = /home/nre/<redacted>/ansible.cfg
  configured module search path = ['/home/nre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nre/<redacted>/lib/python3.8/site-packages/ansible
  executable location = /home/nre/<redacted>/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
$ ansible-lint --version
ansible-lint 5.0.0
```

- ansible installation method: pip
- ansible-lint installation method: pip
