### ISSUE TITLE
Inconsistent role self-referencing in Molecule vs ansible-lint v5

### ISSUE THREAD

**Issue by brianhelba** [ansible-community/ansible-lint#1485]
##### Summary
In ansible-lint v5, it's not clear how the the `converge.yml` file should refer back to the role itself.

Starting in ansible-lint v5, it seems that the role's root directory was not longer included in the list of role search paths. Instead, the role's root directory is symlinked from `.cache/roles/{galaxy_info.author}.{galaxy_info.role_name}` and `.cache/roles` is included in the role search paths.

For the upgrade to ansible-lint v5, I had to change the `converge.yml` file (I'll use my role https://github.com/girder/ansible-role-girder-mongodb as an example) from:
```yml
---
- name: Converge
  hosts: all
  roles:
    # Satisfies ansible-lint v4 and molecule
    - role: ansible-role-girder-mongodb
```
to
```yml
---
- name: Converge
  hosts: all
  roles:
    # Satisfies ansible-lint v5 only
    - role: girder.mongodb
```

However, as noted, Molecule itself still includes the role's root directory in the role search paths. Since my role is on the filesystem at `/home/user/projects/ansible-role-girder-mongodb` (in keeping with the name of the role repository itself), Molecule can find `role: ansible-role-girder-mongodb` but it cannot find `role: girder.mongodb`.

So, how should `converge.yml` refer back to the role itself to satisfy both ansible-lint v5 and Molecule? I'd be happy to post more detailed error logs if necessary, but I hope this description is sufficient to understand the issue. I'm filing this issue here in the ansible-lint repo, just because it has had the most recent changes to trigger this problem.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
$ ansible-lint --version
ansible-lint 5.0.4 using ansible 2.10.6

$ molecule --version
molecule 3.2.4 using python 3.9 
    ansible:2.10.6
    delegated:3.2.4 from molecule
    docker:0.2.4 from molecule_docker
```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

##### OS / ENVIRONMENT
Linux
