### ISSUE TITLE
noqa comment parsing does not work for multi-line YAML commands

### ISSUE THREAD

**Issue by nre-ableton** [ansible-community/ansible-lint#1547]
##### Summary

The following `noqa` suppression works perfectly with ansible-lint:

```yaml
- name: Install Virtualenv
  become: true
  command: pip-3.8 install --upgrade virtualenv # noqa no-changed-when
```

However, this one does not:

```yaml
- name: Install Virtualenv
  become: true
  command: >  # noqa no-changed-when
    pip-3.8 install --upgrade --prefix='/usr/local' virtualenv
```

In the latter case, the `no-changed-when` violation is raised.

I'm pretty sure this hasn't been reported yet, but https://github.com/ansible-community/ansible-lint/issues/1506 might be related.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details
```console (paste below)
$ ansible --version
ansible 2.10.5
  config file = /home/nre/Code/<redacted>/ansible.cfg
  configured module search path = ['/home/nre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nre/Code/caches/venv/<redacted>/lib/python3.8/site-packages/ansible
  executable location = /home/nre/Code/caches/venv/<redacted>/bin/ansible
  python version = 3.8.6 (default, Jan 27 2021, 15:42:20) [GCC 10.2.0]

$ ansible-lint --version
ansible-lint 5.0.7 using ansible 2.10.5


```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

##### OS / ENVIRONMENT

Ubuntu Linux 20.04.
