### ISSUE TITLE
False positive: async jobs

### ISSUE THREAD

**Issue by bluikko** [ansible-community/ansible-lint#1588]
##### Summary

A `command` module task that is run as an async job is incorrectly treated as a normal sync task.

For async tasks the options like `changed_when` (and `failed_when` and so on) are not given to the async `command` task itself, they are given to the `async_status` module task that is run after the async task.

Ansible-lint does not understand this and complains for rule `no-changed-when` for the `command` task.

Example:
```yaml
---
- name: Asynchronous long task
  command: alongtask.sh
  async: 1000
  poll: 0
  register: job_sleeper

- name: Wait for asynchronous job to end
  async_status:
    jid: '{{ job_sleeper.ansible_job_id }}'
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10
  changed_when: [....]
```

Note how the `changed_when` is given in the `async_status` task and not in the `command` task.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
2.9.21

ansible-lint --version
5.0.8

```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

EL7.9 all updated

##### STEPS TO REPRODUCE

```yaml
---
- name: Asynchronous yum task
  command: alongtask.sh
  async: 1000
  poll: 0
  register: job_sleeper

- name: Wait for asynchronous job to end
  async_status:
    jid: '{{ job_sleeper.ansible_job_id }}'
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10
  changed_when: [....]
```

```console (paste below)

```

##### Desired Behaviour

Ansible-lint should not detect `no-changed-when` for `command` module task run as async job since the `changed_when` cannot be given to the `command` module task itself.

It should detect that there is a `changed_when` in the following `async_status` task.

##### Actual Behaviour

Ansible-lint detects false positive `no-changed-when` for `command` module task run as async job even though `changed_when` cannot be correctly given for an async task - the `changed_when` is given for the subsequent `async_status` module task.

```paste below

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
