### ISSUE TITLE
yamllint config not extending correctly

### ISSUE THREAD

**Issue by jantari** [ansible-community/ansible-lint#1777]
##### Summary

I want to be able to configure some of yamllints rules when running ansible-lint
with a custom yamllint configuration file that is merged with ansible-lints built-in yamllint configuration.

From #1344 I gather this should be possible.

However some settings I did not extend/overwrite are different when a custom yamllint config file
is present vs when there is none. See "Steps to reproduce" for details.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
# ansible --version
ansible [core 2.11.2]
  config file = /home/jantari/gitlab/platforms/fortigates-new/ansible.cfg
  configured module search path = ['/home/jantari/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jantari/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/jantari/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jantari/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True

# ansible-lint --version
ansible-lint 5.3.0 using ansible 2.11.2
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE

I have a repository where, without any ansible-lint or yamllint config done,
I get back  these results from ansible-lint:

```
Finished with 110 failure(s), 0 warning(s) on 66 files.
```

all 110 failures are from "yaml". I now want to relax some of yamllints rules to align with our style requirements,
so I added the following file to the root of the repository as `.yamllint.yml`:

```yaml
---

extends: relaxed

rules:
  comments:
    min-spaces-from-content: 1
```

( I tried both `extends: default` and `extends: relaxed` but similar results )

I get the message `Loading custom .yamllint.yml config file, this extends our internal yamllint config.`
so I know my config was extended / merged. However, despite my custom config being a relaxation of the rule,
I now get back:

```
Finished with 234 failure(s), 0 warning(s) on 66 files.
```

When looking at the results, this is mostly because of the `line-length` linting rule. Before my custom yamllint config was used, I only had a few results that looked like this - the limit was set to 160 characters:

```
yaml: line too long (177 > 160 characters) (line-length)
```

However when my custom yamllint config is included, the limit is reduced to just 80 characters even though I did not do that in my config:

```
yaml: line too long (89 > 80 characters) (line-length)
```

which leads to all these additional linter errors.

##### Desired Behaviour

When a custom yamllint configuration file is present that extends the default config then only the settings that are actually
in yhe configuration file should be changed. The `line-length` rule should not be affected.

##### Actual Behaviour

Minimum complete verifiable example:

<details>

### playbook

Save the following file as `problematic-yaml.yml`:

```yaml
---

one_space_from_comment: value # comment
two_space_from_comment: value  # comment

over_80_chars: 1234567890123456789012345678901234567890123456789012345678901234567890
over_160_chars: 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
```

### yamllint config

Save the following file as `.yamllint.yml`:

```yaml
---

extends: default

rules:
  comments:
    min-spaces-from-content: 1
```

### To reproduce

Run `ansible-lint` in this directory with the `.yamllint.yml` file present and named as such and then rename the fole (for example to `.yamllint.yml_disabled`) and run `ansible-lint` again.

WITHOUT the yamllint config file being loaded the output is:

```
WARNING  Listing 2 violation(s) that are fatal
yaml: too few spaces before comment (comments)
problematic-yaml.yml:3

yaml: line too long (196 > 160 characters) (line-length)
problematic-yaml.yml:7

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - yaml  # Violations reported by yamllint

Finished with 2 failure(s), 0 warning(s) on 1 files.
```

WITH the yamllint config file present and loaded the output is:

```
Loading custom .yamllint.yml config file, this extends our internal yamllint config.
WARNING  Listing 2 violation(s) that are fatal
yaml: line too long (85 > 80 characters) (line-length)
problematic-yaml.yml:6

yaml: line too long (196 > 80 characters) (line-length)
problematic-yaml.yml:7

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - yaml  # Violations reported by yamllint

Finished with 2 failure(s), 0 warning(s) on 1 files.
```

even though the `line-length` rule was not touched.

</details>
