### ISSUE TITLE
E104: with_flattened and single items

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-community/ansible-lint#315]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.4.2.0
ansible-lint 3.4.17
```

- ansible installation method: OS package
- ansible-lint installation method: OS package

# Actual Behaviour (Bug report only)

Checking this:
```
- name: activate gpg-check for yum-repos
  replace:
    dest: '{{ item }}'
    regexp: '^\s*gpgcheck: 0'
    replace: 'gpgcheck: 1'
  with_flattened:
    - '/etc/yum.conf'
```

..gives this message:
```[ANSIBLE0015] Found a bare variable '['/etc/yum.conf']' used in a 'with_flattened' loop. You should use the full variable syntax ('{{['/etc/yum.conf']}}')```

However the recommendation is wrong and produces an error.
This does work:
```  with_flattened:
    - ['/etc/yum.conf']
```

# Desired Behaviour

This should work and not produce any errors:
```
- name: activate gpg-check for yum-repos
  replace:
    dest: '{{ item }}'
    regexp: '^\s*gpgcheck: 0'
    replace: 'gpgcheck: 1'
  with_flattened:
    - '/etc/yum.conf'
```
