### ISSUE TITLE
[503] "Tasks that run when changed should likely be handlers" is too opinionated and annoying

### ISSUE THREAD

**Issue by geerlingguy** [ansible-community/ansible-lint#419]
# Issue Type

- Bug report

# Ansible and Ansible Lint details

```
$ ansible --version
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jeff.geerling/.ansible/plugins/modules',u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

$ ansible-lint --version
ansible-lint 3.5.1
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

Reacting to a change (e.g. `when: something.changed`) is useful for many scenarios where using a handler is way too heavyweight.

# Actual Behaviour (Bug report only)

If I do something like "clone a repo, if it was changed, do xyz before doing other things", then I get the following report:

```
[503] Tasks that run when changed should likely be handlers
/Users/jeff.geerling/Dropbox/VMs/roles/geerlingguy.drush/tasks/install-source.yml:17
Task/Handler: Ensure Drush can be installed on Debian Wheezy.

[503] Tasks that run when changed should likely be handlers
/Users/jeff.geerling/Dropbox/VMs/roles/geerlingguy.drush/tasks/install-source.yml:26
Task/Handler: Install Drush dependencies with Composer.
```

Here's that example code:

```yaml
- name: Clone Drush from GitHub.
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: "{{ drush_source_install_path }}"
    version: "{{ drush_source_install_version }}"
    update: "{{ drush_keep_updated }}"
    force: "{{ drush_force_update }}"
    depth: "{{ drush_clone_depth }}"
  register: drush_clone

- name: Check for composer.json
  stat: path={{ drush_source_install_path }}/composer.json
  register: drush_composer

# See: https://github.com/geerlingguy/ansible-role-drush/issues/6
- name: Ensure Drush can be installed on Debian Wheezy.
  command: >
    {{ composer_path }} update {{ drush_composer_cli_options }}
    chdir={{ drush_source_install_path }}
  when:
    - drush_clone.changed and ansible_distribution == "Debian"
    - ansible_distribution_release == "wheezy"
    - drush_composer.stat.exists

- name: Install Drush dependencies with Composer.
  command: >
    {{ composer_path }} install {{ drush_composer_cli_options }}
    chdir={{ drush_source_install_path }}
  when: (drush_clone.changed and drush_composer.stat.exists) or drush_force_composer_install
```

Actual code: https://github.com/geerlingguy/ansible-role-drush/blob/master/tasks/install-source.yml#L2-L25

I have rewritten these tasks to use handlers, and it ends up being an extra 5-10 lines of code overall, and it makes the flow of the tasks way more complex... plus I have to do a `meta: flush_handlers` inline, since I need the follow-up tasks to execute _now_ before other parts of my role (which could be affected by the new code) have a chance to run.

I think having to call `meta: flush_handlers` can also be slightly dangerous (and IMO is a code smell) because you might be calling a bunch of other handlers if nothing else has flushed them by the time this particular role runs.

While I think this is a warning and not an 'error', it still dings my module's 'quality score' on Ansible Galaxy, and also fails my builds in Travis CI (exit code is `2` and not `0`), so I would vote for dropping it entirely, or finding a way to report it as more a general info thing (instead of exiting with a non-0 failure).
