### ISSUE TITLE
Syntax Error while loading YAML.   could not determine a constructor for the tag '!encrypted/pkcs1-oaep'

### ISSUE THREAD

**Issue by aakarshg** [ansible-community/ansible-lint#536]
# Issue Type
- Bug report
- Feature request

# Ansible and Ansible Lint details

```
ansible-lint --version 4.0.1 but can probably be seen in other versions as well
```

Might not be a bug with ansible-lint but, can probably help others who came across a similar issue with ansible-lint failing on files with tags.

The only way to get around having tags in yaml file, and not have ansible-lint throw errors at it is if the file is excluded.

Part of the .yaml file I'd was:

```yaml
- secret:
    name: <some_name>
    data:
      user: <some_user>
      host: github.com
      host_key: <some_value >
      ssh_key: !encrypted/pkcs1-oaep # Issue arises here
```
The error was `Syntax Error while loading YAML.
  could not determine a constructor for the tag '!encrypted/pkcs1-oaep'`

# Workaround

I was using pre-commit here to invoke ansible-lint, so I added the file to exclude list. And it looked as follows.

```
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.0.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: ^(some_dir/|\.issue_file\.yaml)
        entry: ansible-lint --force-color -v
```

Just an interesting point to be noted here is that when using pre-commit, pre-commit identifies each modified file and sends it directly to the linter, so adding exclude to the .ansible-lint file doesn't work. Thanks to @ssbarnea who helped me with it.
