### ISSUE TITLE
Ansible-lint should catch invalid attributes

### ISSUE THREAD

**Issue by MaciejKucia** [ansible-community/ansible-lint#539]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
ansible --version
ansible 2.5.15
ansible-lint --version
ansible-lint 4.0.1
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

During Ansible play linted playbooks and roles should not report following warning:
```
[WARNING]: Ignoring invalid attribute: backup
```

Sample invalid part of role:
```
- name: Configure nfs
  backup: yes
  template:
    src: nfs.j2
    dest: /etc/nfs
```
