### ISSUE TITLE
tags not being skipped

### ISSUE THREAD

**Issue by carlbuchmann** [ansible-community/ansible-lint#547]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version
ansible 2.7.10
ansible-lint --version
ansible-lint 4.1.0
```

- ansible installation method: one of source, pip, OS package: yum
- ansible-lint installation method: one of source, pip, OS package: pip

# Desired Behaviour

Skip list tag, should skip the specified tag.

## .ansible-lint contains skip tag:
```
skip_list:
  - patching
```

## tasks contain tag:
```
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  notify: reboot host
  tags:
    - update
    - patching
```

# Actual Behaviour (Bug report only)

## linting should skip and reports error:

```
ansible-lint atd-centos.yml
[403] Package installs should not use latest
/home/carlbuchmann/github-projects/atd/ansible-labvm-CentOS/roles/update/tasks/main.yml:1
Task/Handler: upgrade all packages
```

## works if I specify:

```
skip_list:
  - '403'
```

## .ansible-lint contains skip tag:
```
skip_list:
  - skip_ansible_lint
```

## tasks contain "skip_ansible_lint" tag:

```
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  notify: reboot host
  tags:
    - update
    - skip_ansible_lint
```

Why does it fail with tag "patching"?
