### ISSUE TITLE
add rule to flag short-hand syntax

### ISSUE THREAD

**Issue by reduzent** [ansible-community/ansible-lint#609]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
ansible 2.8.5
ansible-lint 4.1.0
```

- ansible installation method: pip
- ansible-lint installation method:  pip

# Desired Behaviour

Add a rule to flag lines that make use of the old ansible short-hand syntax.

This would be flagged:

```
- name: configure service
  template: src=config.file.j2 dest=/etc/service/config.cfg
```

while this won't:

```
- name: configure service
  template:
    src: config.file.j2
    dest: /etc/service/config.cfg
```
